describe('Outbound Page', () => {
  beforeEach(() => {
    cy.intercept("POST", "https://equilibrium.herokuapp.com/graphql", {
      fixture: "data1.json"
    })
    cy.visit('http://localhost:3000/outbound')
  });

  it('Should have a list of project contributers', () => {
    cy.get('[data-cy="outbound-container"]')
      .should('exist')
  })

  it('Should have a thank you message', () => {
    cy.get('[data-cy="thanks"]')
      .should('exist')
      .contains('Thank you for viewing our application.')
  })

  it('Should have links to all of the creators\' Github and LinkedIn profiles', () => {
    cy.get('[data-cy="ali"]')
      .should('exist')
      .get('[data-cy="ali"] > h4')
      .should('exist')
      .contains('Ali Nix')
      .get('[data-cy="ali"] > .github')
      .should('exist')
      .get('[data-cy="ali"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="ali"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="ali"] > .linkedin')
      .should('exist')
      .get('[data-cy="ali"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="ali"] > .linkedin > .webLink')
      .should('exist')

    cy.get('[data-cy="candace"]')
      .should('exist')
      .get('[data-cy="candace"] > h4')
      .should('exist')
      .contains('Candace Eckels')
      .get('[data-cy="candace"] > .github')
      .should('exist')
      .get('[data-cy="candace"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="candace"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="candace"] > .linkedin')
      .should('exist')
      .get('[data-cy="candace"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="candace"] > .linkedin > .webLink')
      .should('exist')

    cy.get('[data-cy="dana"]')
      .should('exist')
      .get('[data-cy="dana"] > h4')
      .should('exist')
      .contains('Dana Chapman')
      .get('[data-cy="dana"] > .github')
      .should('exist')
      .get('[data-cy="dana"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="dana"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="dana"] > .linkedin')
      .should('exist')
      .get('[data-cy="dana"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="dana"] > .linkedin > .webLink')
      .should('exist')

    cy.get('[data-cy="emily"]')
      .should('exist')
      .get('[data-cy="emily"] > h4')
      .should('exist')
      .contains('Emily Miles')
      .get('[data-cy="emily"] > .github')
      .should('exist')
      .get('[data-cy="emily"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="emily"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="emily"] > .linkedin')
      .should('exist')
      .get('[data-cy="emily"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="emily"] > .linkedin > .webLink')
      .should('exist')

    cy.get('[data-cy="taryn"]')
      .should('exist')
      .get('[data-cy="taryn"] > h4')
      .should('exist')
      .contains('Taryn Orlemann')
      .get('[data-cy="taryn"] > .github')
      .should('exist')
      .get('[data-cy="taryn"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="taryn"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="taryn"] > .linkedin')
      .should('exist')
      .get('[data-cy="taryn"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="taryn"] > .linkedin > .webLink')
      .should('exist')

    cy.get('[data-cy="thomas"]')
      .should('exist')
      .get('[data-cy="thomas"] > h4')
      .should('exist')
      .contains('Thomas Hayes')
      .get('[data-cy="thomas"] > .github')
      .should('exist')
      .get('[data-cy="thomas"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="thomas"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="thomas"] > .linkedin')
      .should('exist')
      .get('[data-cy="thomas"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="thomas"] > .linkedin > .webLink')
      .should('exist')
    
    cy.get('[data-cy="will"]')
      .should('exist')
      .get('[data-cy="will"] > h4')
      .should('exist')
      .contains('Will Hobson')
      .get('[data-cy="will"] > .github')
      .should('exist')
      .get('[data-cy="will"] > .github > .github-icon')
      .should('exist')
      .get('[data-cy="will"] > .github > .webLink')
      .should('exist')
      .get('[data-cy="will"] > .linkedin')
      .should('exist')
      .get('[data-cy="will"] > .linkedin > .linkedin-icon')
      .should('exist')
      .get('[data-cy="will"] > .linkedin > .webLink')
      .should('exist')
  })

  it('Should be able to go back to the Landing Page', () => {
    cy.get('button')
      .click()
      cy.url().should('eq', 'http://localhost:3000/')
  })
})